# Generated by Django 3.0 on 2019-12-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='representants_id')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='adresse')),
                ('zipcode', models.CharField(blank=True, max_length=256, verbose_name='code_postal')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='derniere_publication_activite')),
                ('first_activity', models.DateTimeField(blank=True, null=True, verbose_name='date_premiere_publication')),
                ('organizations', models.BooleanField(default=False, verbose_name='declaration_organisation_appartenance')),
                ('third_parties', models.BooleanField(default=False, verbose_name='declaration_tiers')),
                ('name', models.CharField(max_length=256, verbose_name='denomination')),
                ('nif', models.CharField(max_length=256, unique=True, verbose_name='identifiant_national')),
                ('activities', models.BooleanField(default=False, verbose_name='activites_publiees')),
                ('facebook', models.URLField(blank=True, verbose_name='page_facebook')),
                ('linkedin', models.URLField(blank=True, verbose_name='page_linkedin')),
                ('twitter', models.URLField(blank=True, verbose_name='page_twitter')),
                ('website', models.URLField(blank=True, verbose_name='site_web')),
                ('hatvp_name', models.CharField(max_length=256, verbose_name='nom_usage_HATVP')),
                ('country', models.CharField(max_length=32, verbose_name='pays')),
                ('acronym', models.CharField(max_length=32, verbose_name='sigle_HATVP')),
                ('nif_type', models.CharField(max_length=8, verbose_name='type_identifiant_national')),
                ('town', models.CharField(max_length=64, verbose_name='ville')),
                ('category', models.CharField(max_length=64, verbose_name='label_categorie_organisation')),
            ],
        ),
    ]
