# Generated by Django 3.0 on 2019-12-09 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='denomination_affiliation')),
                ('nif', models.CharField(max_length=16, verbose_name='identifiant_national_affiliation')),
                ('nif_type', models.CharField(max_length=16, verbose_name='type_identifiant_national_affiliation')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='representants_id')),
            ],
        ),
    ]
