# Generated by Django 3.0 on 2019-12-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0002_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('civility', models.CharField(max_length=8, verbose_name='civilite_dirigeant')),
                ('function', models.CharField(max_length=256, verbose_name='fonction_dirigeant')),
                ('lastname', models.CharField(max_length=64, verbose_name='nom_dirigeant')),
                ('firstname', models.CharField(max_length=64, verbose_name='prenom_dirigeant')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='representants_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='denomination_client')),
                ('nif', models.CharField(max_length=16, verbose_name='identifiant_national_client')),
                ('nif_type', models.CharField(max_length=16, verbose_name='type_identifiant_national_client')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='representants_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('civility', models.CharField(max_length=8, verbose_name='civilite_collaborateur')),
                ('function', models.CharField(max_length=256, verbose_name='fonction_collaborateur')),
                ('lastname', models.CharField(max_length=64, verbose_name='nom_collaborateur')),
                ('firstname', models.CharField(max_length=64, verbose_name='prenom_collaborateur')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='representants_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
