# Generated by Django 3.0 on 2019-12-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0003_auto_20191209_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('1', 'Local'), ('2', 'National'), ('3', 'Européen'), ('4', 'Mondial')], max_length=1, verbose_name='niveau_intervention')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='representants_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
