# Generated by Django 3.0 on 2019-12-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0004_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='exercices_id')),
                ('incomplete_declaration', models.BooleanField(default=False, verbose_name='declaration_incomplete')),
                ('publication', models.DateField(blank=True, null=True, verbose_name='date_publication')),
                ('amount', models.CharField(max_length=128, verbose_name='montant_depense')),
                ('min_amount', models.FloatField(verbose_name='montant_depense_inf')),
                ('max_amount', models.FloatField(verbose_name='montant_depense_sup')),
                ('no_activity', models.BooleanField(default=False, verbose_name='exercice_sans_activite')),
                ('nb_activities', models.PositiveIntegerField(default=0, verbose_name='nombre_activites')),
                ('start', models.DateField(blank=True, null=True, verbose_name='date_debut')),
                ('end', models.DateField(blank=True, null=True, verbose_name='date_fin')),
                ('start_year', models.PositiveIntegerField(verbose_name='annee_debut')),
                ('end_year', models.PositiveIntegerField(verbose_name='annee_fin')),
                ('nb_employees', models.FloatField(verbose_name='nombre_salaries')),
                ('no_turnover', models.BooleanField(default=False, verbose_name='exercice_sans_CA')),
                ('turnover', models.CharField(max_length=128, verbose_name='chiffre_affaires')),
                ('min_turnover', models.FloatField(verbose_name='ca_inf')),
                ('max_turnover', models.FloatField(verbose_name='ca_sup')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='representants_id')),
            ],
        ),
    ]
