# Generated by Django 3.0 on 2019-12-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0005_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='nb_employees',
            field=models.FloatField(default=0, verbose_name='nombre_salaries'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='activite_id')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date_publication_activite')),
                ('ref', models.CharField(max_length=8, verbose_name='identifiant_fiche')),
                ('desc', models.TextField(verbose_name='objet_activite')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.Period', verbose_name='exercices_id')),
            ],
        ),
    ]
