# Generated by Django 3.0 on 2019-12-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0006_auto_20191216_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='desc',
        ),
    ]
