# Generated by Django 3.0 on 2019-12-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0007_remove_activity_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='responsable_public')),
                ('department', models.CharField(max_length=128, verbose_name='departement_ministeriel')),
                ('more', models.CharField(max_length=128, verbose_name='responsable_public_ou_dpt_ministeriel_autre')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='action_representation_interet_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=128, verbose_name='activite_id')),
                ('observation', models.TextField(verbose_name='observation')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='action_representation_interet_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='secteur_activite')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='representants_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='domaines_intervention_actions_menees')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.Activity', verbose_name='activite_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='decision_concernee')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='action_representation_interet_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='action_menee')),
                ('own', models.BooleanField(default=False, verbose_name='action_menee_en_propre')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='action_representation_interet_id')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='action_menee')),
                ('more', models.TextField(verbose_name='action_menee_autre')),
                ('representant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.GeneralInformation', verbose_name='action_representation_interet_id')),
            ],
        ),
    ]
