# Generated by Django 3.0 on 2019-12-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0009_auto_20191217_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='representant',
        ),
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='action_representation_interet_id'),
        ),
    ]
