# Generated by Django 3.0 on 2019-12-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0010_auto_20191217_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='action',
            name='more',
        ),
        migrations.CreateModel(
            name='TypeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='action_menee')),
                ('more', models.TextField(verbose_name='action_menee_autre')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.Action', verbose_name='action_representation_interet_id')),
            ],
        ),
    ]
